Eric mp branch
wrongkindofdoctor/FMS pull request #44
Opened 2020-09-02 21:49 UTC by GFDL-Eric

**Description**
Created a unit test for mpp_min and mpp_max interfaces with 32-bit and 64-bit real arrays.

**How Has This Been Tested?**
Just Skylake with Intel so far... more tests welcome!

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

2020-09-02 22:35 UTC, ngs333 commented on test_fms/mpp/test_minmax.F90
> +program test   !test mpp_min and mpp_max functions for various ints and reals
I think we are trying to use doxygen style comments for new code. Some annotations we have used are:
@author @brief @email , @description , @todo
You can see here fro more info: https://www.doxygen.nl/manual/docblocks.html#docstructure

2020-09-02 22:43 UTC, ngs333 commented on test_fms/mpp/test_minmax.F90
> +  call mpp_max( a(1) )
cant you add an if statement to check if the value determined by mpp_max is what it should be, and if not call  cmpp_error(FATAL, " message")

2020-09-02 22:44 UTC, ngs333 commented on test_fms/mpp/test_minmax.F90
> +     if( pe.EQ.root )print *, 'max(pe+1) from 0 to npes-2=', a(1)
cant you add an if statement to check if the value determined by mpp_max is what it should be, and if not call mpp_error(FATAL, " message")

2020-09-02 22:45 UTC, ngs333 commented on test_fms/mpp/test_minmax.F90
> +     if( pe.EQ.root )print *, 'min(pe+1) from 0 to npes-2=', a(1)
can't you add an if statement to check if the value determined by mpp_max is what it should be, and if not call mpp_error(FATAL, " message") ?  Similar issues follow below.

2020-09-03 19:11 UTC, wrongkindofdoctor requested changes

2020-09-03 19:11 UTC, wrongkindofdoctor commented on test_fms/mpp/test_minmax.F90
> +#include <fms_platform.h>
remove #include <fms_platform.h>, add use :: platform_mod, and change the type definitions.

2020-09-09 16:17 UTC, GFDL-Eric commented on test_fms/mpp/test_minmax.F90
> +#include <fms_platform.h>
Updated with commit cf4c4426765b7d575b1eccbc7a11474b2fdd6f73

2020-09-09 16:19 UTC, GFDL-Eric commented on test_fms/mpp/test_minmax.F90
> +program test   !test mpp_min and mpp_max functions for various ints and reals
Added in commit 3f3be3e9931c047098530fab532069b4629c17d4

2020-09-09 16:19 UTC, GFDL-Eric commented on test_fms/mpp/test_minmax.F90
> +  call mpp_max( a(1) )
Added in commit 3f3be3e9931c047098530fab532069b4629c17d4

2020-09-09 16:19 UTC, GFDL-Eric commented on test_fms/mpp/test_minmax.F90
> +     if( pe.EQ.root )print *, 'max(pe+1) from 0 to npes-2=', a(1)
Added in commit 3f3be3e9931c047098530fab532069b4629c17d4

2020-09-09 16:19 UTC, GFDL-Eric commented on test_fms/mpp/test_minmax.F90
> +     if( pe.EQ.root )print *, 'min(pe+1) from 0 to npes-2=', a(1)
Added in commit 3f3be3e9931c047098530fab532069b4629c17d4

2020-09-09 16:20 UTC, GFDL-Eric commented
Hi everyone,

I pushed a few changes here (I did a force push so I'd recommend deleting any local versions and re-pulling if you want to test).

2020-09-09 20:36 UTC, GFDL-Eric commented
Rebased off of 6b92383

2020-09-10 17:37 UTC, wrongkindofdoctor approved these changes

2020-09-10 17:37 UTC, merged