Adds integer checksum test and removes #ifndef no_8byte_int from mpp
wrongkindofdoctor/FMS pull request #57
Opened 2020-09-23 15:15 UTC by rem1776

**Description**
Takes out the 8byte int ifdefs from all files in mpp and adds a subroutine to test_mpp.F90 that tests checksums on mixed precision integers.

**How Has This Been Tested?**
make check on skylake with intel 20 compiler

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

2020-09-23 19:12 UTC, GFDL-Eric approved these changes
Compiles on Skylake!

2020-09-25 13:50 UTC, wrongkindofdoctor requested changes

2020-09-25 13:50 UTC, wrongkindofdoctor commented on test_fms/mpp/test_chksum_int.F90
> +  call mpp_init()
Add the appropriate [t_level argument](https://github.com/NOAA-GFDL/FMS/blob/4d38679c1e18e920feb03d69f8a9762eb6a047aa/mpp/mpp.F90#L1367) to [`mpp_init()`](https://github.com/NOAA-GFDL/FMS/blob/4d38679c1e18e920feb03d69f8a9762eb6a047aa/mpp/include/mpp_comm_mpi.inc#L28)

2020-09-25 13:50 UTC, wrongkindofdoctor commented on test_fms/mpp/test_chksum_int.F90
> +  call mpp_exit()
replace `mpp_exit()` with `call MPI_FINALIZE(ierr)`

2020-09-25 17:11 UTC, wrongkindofdoctor approved these changes

2020-09-25 17:11 UTC, merged