Add mixed precision
wrongkindofdoctor/FMS pull request #73
Opened 2020-10-23 15:33 UTC by ngs333

**Description**
Modified test_mpp_domains.F90 : 
a) so that test_update_nest_domains functions work (with intel compiler, 16 PEs) by  fixing its namelist. 
 b) created R4 and R8 versions of test_update_nest_domains function.
 c) extracted fill coarse_data and fill_nest_data functions and placed them in their own
     module (in file test_domains_utility_mod.F90) to more easily make and use the r8 and r8 
     (and in the future i4 and i8)versions of them.

Also added to the comments of test_mpp_domains2.sh.

It is expected further work on these same wiles will be done for the i4 and i8 versions of the functions mentioned above.

**How Has This Been Tested?**
This branch was reversed merge with https://github.com/wrongkindofdoctor/FMS/tree/add_mixed_precision (of Oct 22, 2020) compiled with intel 20 compiler and run with   test_mpp_update_domains2.sh with the nest updates test enabled wiith 16 PEs.

**Checklist:**
- [X ] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings
- [X ] Any dependent changes have been merged and published in downstream modules
- [ X] New check tests, if applicable, are included
- [ X] `make distcheck` passes

2020-10-23 20:33 UTC, wrongkindofdoctor requested changes

2020-10-23 20:33 UTC, wrongkindofdoctor commented on test_fms/mpp/test_domains_utility_mod.F90
> +
The mpp_update_nest_coarse and mpp_update_nest_fine interfaces also need to be extended for I4 and I8 values, so it would make sense to go ahead and add tests for them to this PR.

2020-10-23 20:43 UTC, ngs333 commented on test_fms/mpp/test_domains_utility_mod.F90
> +
Yes I know, but that may be more involved and I don't know when I can get to it next. Besides, this merge addresses the bug that was there that would not allow testing.

2020-10-23 20:52 UTC, wrongkindofdoctor commented on test_fms/mpp/test_domains_utility_mod.F90
> +
All right. We'll leave the integer extensions for another PR.

2020-10-23 20:59 UTC, ngs333 commented on test_fms/mpp/test_domains_utility_mod.F90
> +
Thanks!

2020-10-23 21:01 UTC, wrongkindofdoctor commented on test_fms/mpp/test_mpp_domains.F90
> +    !!call mpp_memuse_end(trim(type)//" mpp_define_mosaic", outunit )
Are the `call mpp_memuse_begin/end` lines commented out because they cause errors, or because they are used for debugging only? If it's the former, you can delete them; if it's the latter, please add notes in the comments explaining they are for debugging.

2020-10-23 21:04 UTC, ngs333 commented on test_fms/mpp/test_mpp_domains.F90
> +    !!call mpp_memuse_end(trim(type)//" mpp_define_mosaic", outunit )
Yes, I am tempted to take them out, but I suspect that when in the Future we meld Rustys version, mi might want them be back in. But I guess when that point comes we can collaborate with him for an acceptable resolution.

2020-10-23 21:14 UTC, ngs333 commented on test_fms/mpp/test_mpp_domains.F90
> +    !!call mpp_memuse_end(trim(type)//" mpp_define_mosaic", outunit )
Updated the code.

2020-10-23 21:31 UTC, wrongkindofdoctor commented on test_fms/mpp/test_mpp_domains.F90
> +    !!call mpp_memuse_end(trim(type)//" mpp_define_mosaic", outunit )
Yes, we can always put them back. Thanks!

2020-10-26 13:50 UTC, wrongkindofdoctor commented on test_fms/mpp/test_domains_utility_mod.F90
> +     real(kind=r8_kind),                          intent(in) :: xadd, yadd
Should this be r4_kind ?

2020-10-26 14:23 UTC, ngs333 commented on test_fms/mpp/test_domains_utility_mod.F90
> +     real(kind=r8_kind),                          intent(in) :: xadd, yadd
No. This is not part of the interface that we are testing with MP.  Also, the way I have it, fill_nest_data will handle the various kinds of literal constants that test_mpp_domains.F90 is calling it with. I tried r4 and combinations of r4 and r8, but this  was the best.

2020-10-26 14:31 UTC, wrongkindofdoctor commented on test_fms/mpp/test_domains_utility_mod.F90
> +     real(kind=r8_kind),                          intent(in) :: xadd, yadd
Got it. Thanks.

2020-10-26 14:31 UTC, wrongkindofdoctor approved these changes

2020-10-26 18:06 UTC, merged