Add test_mpp_transmit
wrongkindofdoctor/FMS pull request #75
Opened 2020-10-28 17:47 UTC by laurenchilutti

**Description**
Adding test_mpp_transmit which supports r4, r8, i4, and i8

Fixes # (issue)

**How Has This Been Tested?**
Tested on Gaea using compilers loaded with fre/bronx-18

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

2020-10-28 21:07 UTC, wrongkindofdoctor requested changes

2020-10-28 21:07 UTC, wrongkindofdoctor commented on test_fms/mpp/test_mpp_transmit.F90
> +    c8 = real(modulo(int(a8(1,1))+npes-1,npes), kind=i8_kind)
`modulo(a8(1,1)+npes-1,npes)`?

2020-10-28 21:07 UTC, wrongkindofdoctor commented on test_fms/mpp/test_mpp_transmit.F90
> +    a8 = real(pe, kind=i8_kind)
`int(pe, kind=i8_kind)`

2020-10-28 21:07 UTC, wrongkindofdoctor commented on test_fms/mpp/test_mpp_transmit.F90
> +    real(kind=i8_kind), dimension(1,1) :: a8, b8, c8
`int(kind=i8_kind)`

2020-10-28 21:07 UTC, wrongkindofdoctor commented on test_fms/mpp/test_mpp_transmit.F90
> +    c4 = real(modulo(int(a4(1,1))+npes-1,npes), kind=i4_kind)
`modulo(a4(1,1)+npes-1,npes)`

2020-10-28 21:07 UTC, wrongkindofdoctor commented on test_fms/mpp/test_mpp_transmit.F90
> +    a4 = real(pe, kind=i4_kind)
`int(pe,kind=i4_kind)`

2020-10-28 21:07 UTC, wrongkindofdoctor commented on test_fms/mpp/test_mpp_transmit.F90
> +    real(kind=i4_kind), dimension(1,1) :: a4, b4, c4
`int(kind=i4_kind)`

2020-10-28 21:07 UTC, wrongkindofdoctor commented on test_fms/mpp/test_mpp_transmit.F90
> +    c8 = real(modulo(int(a8(1))+npes-1,npes), kind=i8_kind)
`modulo(a8(1)+npes-1,npes)`

2020-10-28 21:07 UTC, wrongkindofdoctor commented on test_fms/mpp/test_mpp_transmit.F90
> +    real(kind=i8_kind), dimension(1) :: a8, b8, c8
`int(kind=i8_kind)`

2020-10-28 21:07 UTC, wrongkindofdoctor commented on test_fms/mpp/test_mpp_transmit.F90
> +    a8 = real(pe, kind=i8_kind)
`int(pe, kind=i8_kind)`

2020-10-28 21:07 UTC, wrongkindofdoctor commented on test_fms/mpp/test_mpp_transmit.F90
> +    c4 = real(modulo(int(a4(1))+npes-1,npes), kind=i4_kind)
`modulo(a4(1)+npes-1,npes)`

2020-10-28 21:07 UTC, wrongkindofdoctor commented on test_fms/mpp/test_mpp_transmit.F90
> +    real(kind=i4_kind), dimension(1) :: a4, b4, c4
`int(kind=i4_kind)`

2020-10-28 21:07 UTC, wrongkindofdoctor commented on test_fms/mpp/test_mpp_transmit.F90
> +    a4 = real(pe, kind=i4_kind)
`int(pe, kind=i4_kind)`

2020-10-28 22:02 UTC, ngs333 approved these changes

2020-10-30 13:29 UTC, wrongkindofdoctor approved these changes

2020-10-30 13:36 UTC, mlee03 reviewed
mpp_init accepts several optional arguments, should use mpp_init(test_level=mpp_init_test_requests_allocated) ?

2020-10-30 13:52 UTC, laurenchilutti commented
@mlee03 I updated the mpp_init call to match what you've said.

2020-10-30 14:12 UTC, mlee03 commented on test_fms/mpp/test_mpp_transmit.F90
> +    call mpp_sync()
not sure if it's necessary or not, but b4 is not initialized

2020-10-30 14:12 UTC, mlee03 commented on test_fms/mpp/test_mpp_transmit.F90
> +    call mpp_transmit( put_data=a4(1,1), plen=n, to_pe=modulo(pe+1, npes), &
is it supposed to be put_data=a4?

2020-10-30 14:12 UTC, mlee03 commented on test_fms/mpp/test_mpp_transmit.F90
> +    real(kind=r8_kind), dimension(1,1) :: a8, b8, c8
perhaps something bigger than (1,1)?  I think for (1,1), the size of the array is just 1

2020-10-30 14:32 UTC, wrongkindofdoctor commented on test_fms/mpp/test_mpp_transmit.F90
> +    call mpp_sync()
Yes, it would be good to initialize the arrays.

2020-10-30 16:50 UTC, laurenchilutti commented on test_fms/mpp/test_mpp_transmit.F90
> +    call mpp_sync()
added this in the latest commit

2020-10-30 16:58 UTC, laurenchilutti commented on test_fms/mpp/test_mpp_transmit.F90
> +    call mpp_transmit( put_data=a4(1,1), plen=n, to_pe=modulo(pe+1, npes), &
From testing, this does not work when put_data=a4.  In [mpp_transmit](https://github.com/NOAA-GFDL/FMS/blob/master/mpp/include/mpp_transmit_mpi.h#L81), put_data  is being used as the "buff" input parameter to [MPI_ISEND](https://www.mpich.org/static/docs/latest/www3/MPI_Isend.html).  The "buff" parameter is defined as "initial address of send buffer".  I guess a4(1,1) is the initial address of the send buffer.

2020-10-30 16:58 UTC, laurenchilutti commented on test_fms/mpp/test_mpp_transmit.F90
> +    real(kind=r8_kind), dimension(1,1) :: a8, b8, c8
Good point, I have updated to have dimensions in increments of 2 so we can truly test the capability.

2020-11-04 12:58 UTC, merged