Updated mpp_sum to include r4/r8/i4/i8 testing
wrongkindofdoctor/FMS pull request #78
Opened 2020-11-10 16:12 UTC by laurenchilutti

**Description**
Updated test_mpp_sum to test i4/i8, and reorganized the code

Fixes # (issue)

**How Has This Been Tested?**
tested on gaea with bronx-18

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included
- [x] `make distcheck` passes

2020-11-10 17:45 UTC, ngs333 approved these changes

2020-11-12 13:47 UTC, wrongkindofdoctor requested changes

2020-11-12 13:47 UTC, wrongkindofdoctor commented on test_fms/mpp/test_mpp_sum.F90
> +  subroutine test_mpp_sum_pelist(pe,npes,root)
Please add i4,i8, and r8 versions of test_mpp_sum_pelist and test_mpp_sum_large (I know this is tedious, but the test should verify all of the supported kinds).

2020-11-12 14:17 UTC, laurenchilutti commented on test_fms/mpp/test_mpp_sum.F90
> +  subroutine test_mpp_sum_pelist(pe,npes,root)
Ill do that now!

2020-11-12 20:12 UTC, wrongkindofdoctor approved these changes

2020-11-13 13:52 UTC, merged