added i4_kind and i8_kind version of tests for mpp_update_nest<coarse…
wrongkindofdoctor/FMS pull request #79
Opened 2020-11-12 18:17 UTC by ngs333

This merge adds subroutines tests_update_nest_domains_i4 and  tests_update_nest_domains_i8,
which in turn test the the mpp_update_nest_fine and mpp_update_nest_coarse routines with argument data of
type i4_kind and i8_kind, respectively.

Note that there are now four routines ( tests_update_nest_domains_<i4 | i8, r4, r8> which are essentially copies of the one.
The use all the same index data type, but the domain data passed to the mpp update nest routines vary in type.
I have made an attempt to combine all four of the function into one ( reducing the code into half - or about 17K lines)
but I could not make it work.  It may be possible, if allowed, to one day combine these four by using macros and
variable data types - effectively reducing the SLOC by a factor of four to about 8K.

The unit tests successfully run on the AMD box with the Intel 19 compiler and using 16 PEs.

**Checklist:**
- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings
- [X ] Any dependent changes have been merged and published in downstream modules
- [X ] New check tests, if applicable, are included
- [X ] `make distcheck` passes

2020-11-12 19:48 UTC, wrongkindofdoctor requested changes

2020-11-12 19:48 UTC, wrongkindofdoctor commented on test_fms/mpp/test_mpp_domains.F90
> +    real(kind=i8_kind), allocatable :: x(:,:,:), x1(:,:,:), x2(:,:,:)
this and subsequent arrays should be integer(kind=i8_kind)

2020-11-12 19:48 UTC, wrongkindofdoctor commented on test_fms/mpp/test_mpp_domains.F90
> +    real(kind=i4_kind), allocatable :: x(:,:,:), x1(:,:,:), x2(:,:,:)
This array and subsequent data array should be integer(kind=i4_kind)

2020-11-12 19:52 UTC, ngs333 commented on test_fms/mpp/test_mpp_domains.F90
> +    real(kind=i4_kind), allocatable :: x(:,:,:), x1(:,:,:), x2(:,:,:)
Yikes! How did I do that? :-(

2020-11-12 22:42 UTC, wrongkindofdoctor commented on test_fms/mpp/test_mpp_domains.F90
> +    real(kind=i4_kind), allocatable :: x(:,:,:), x1(:,:,:), x2(:,:,:)
Just when you thought you're find-and-replace game was tight ;-p.

2020-11-12 23:01 UTC, ngs333 commented on test_fms/mpp/test_mpp_domains.F90
> +    real(kind=i4_kind), allocatable :: x(:,:,:), x1(:,:,:), x2(:,:,:)
Thats it! No more bugs or its the guillotine for me! Or better yet, since Rust's type system, borrowing mechanisms, ownership, lifetimes, and concurrency are mathematically proved (See Jung, "RustBelt: Securing the Foundations of the Rust Programming Language") I'll just  move over to Rust and avoid the guillotime!

2020-12-02 20:23 UTC, ngs333 commented
This PR should be cancelled. It was determined that the the actual interfaces themselves that this PR was 
trying to test did not exist. This was not apparent till the requested changed above was done, and then the 
linking step failed, and further investigation into the source code determined that the integer version of the interfaces did not exist.

2020-12-03 15:18 UTC, closed without merging